Repository futurewei-cloud/alcor, pull requests merged in 2020-11, with the labels that each got.

#390 [Documentation] Security Group Host Design
  docs/modules/ROOT/images/router_e2e_workflow.png
  docs/modules/ROOT/images/security_group_workflow.png
  docs/modules/ROOT/pages/high_level/routing_design.adoc
  docs/modules/ROOT/pages/high_level/security_group_host_design.adoc
  docs/modules/ROOT/workflows/router_e2e_workflow.puml
  docs/modules/ROOT/workflows/security_group_workflow.puml
Labels: documentation

#397 [Documentation] Add Routing Rules Update to Route Mgr Design
  docs/modules/ROOT/images/route_manager_l3_neighbors_update_4.PNG
  docs/modules/ROOT/images/route_manager_l3_neighbors_update_5.PNG
  docs/modules/ROOT/images/route_manager_routerinfo_contract.PNG
  docs/modules/ROOT/images/route_manager_routing_rule_update_6.PNG
  docs/modules/ROOT/pages/high_level/routing_design.adoc
  docs/modules/ROOT/pages/mgmt_services/route_manager.adoc
Labels: documentation

#461 [E2E Integration] Fix Subnet Deletion & Router Unbinding Issue
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
Labels: bug

#458 [Data Plane Mgr] UT Test Automation - Part III
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/constants/DPMAutoUnitTestConstant.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
Labels: enhancement, unit test

#418 [Data Plane Mgr] L3 Implementation
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/DataPlaneManager.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/GSController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/DataPlanePrinter.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateHelper.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStatePreparer.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateTransformer.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/constants/DPMAutoUnitTestConstant.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
Labels: feature

#465 [API GW] Customize HTTP header config to Unblock Performance Test
  kubernetes/services/api-gateway.yaml
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/admin/WebServerConfiguration.java
  services/api_gateway/src/main/resources/application.properties
Labels: enhancement, perf testing

#471 [Port Manager] Fix 400 Bad Request for Port List Calls with Excessive URL
  kubernetes/services/port_manager.yaml
  services/api_gateway/pom.xml
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthGwFilter.java
  services/port_manager/src/main/resources/application.properties
Labels: logging

#479 [Contract] Add default_routing_table to Router Configuration
  schema/proto3/auxiliarygateway.proto
  schema/proto3/router.proto
Labels: contract

#472 [Microservice] Data Plane Mgr v2.0 Implementation
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/DataPlaneClient.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/kafka/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/Config.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DataPlaneController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/MulticastGoalState.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/UnicastGoalState.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/GroupTopicNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/MulticastTopicNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortBindingHostIpNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortFixedIpInvalid.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortFixedIpNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortFixedIpRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortIdRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortMacAddressRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortSecurityGroupIdRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortSecurityGroupRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/ProjectIdRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/RouterInfoInvalid.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SecurityGroupRuleNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetCidrRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetGatewayIpRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetGatewayMacRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetIdNotRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetNameRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetPortsInvalid.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetPortsNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/VpcIdRequired.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/DataPlaneService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/DataPlaneServiceNew.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/mizar/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImplNew.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/RestParameterValidator.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/config/TestConfig.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/DataPlaneTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/v2/NetworkConfiguration.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortHostInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/InternalSubnetPorts.java
Labels: feature, refactor

#484 [Contract] Update Contract for DNS/Router, Resolve Discrepancy
  schema/proto3/common.proto
  schema/proto3/dhcp.proto
  schema/proto3/neighbor.proto
  schema/proto3/port.proto
  schema/proto3/router.proto
  schema/proto3/securitygroup.proto
  schema/proto3/subnet.proto
  schema/proto3/vpc.proto
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/Config.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateHelper.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateTransformer.java
  services/data_plane_manager/src/main/resources/application.properties
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
Labels: contract

#481 [Data Plane Mgr] Support Pulsar Publisher
  services/data_plane_manager/pom.xml
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/PulsarConfiguration.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/TopicManager.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/function/MulticastFunction.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/function/UnicastFunction.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/function/function-deploy.sh
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/MulticastGoalState.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/UnicastGoalState.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/TopicParseFailureException.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/resources/application.properties
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/DataPlaneTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/MulticastGoalStateByte.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/UnicastGoalStateByte.java
Labels: feature
