Repository futurewei-cloud/alcor, pull requests merged in 2020-08, with the labels that each got.

#204 [Documentation] Proposal of Alcor Integration with Nova
  docs/modules/ROOT/pages/deploy_related/integration_nova.adoc
Labels: documentation

#337 [Database] Refactor DB Component Scan
  lib/src/main/java/com/futurewei/alcor/common/db/DbBaseConfiguration.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/AlcorApiGatewayApplication.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneConfiguration.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/ElasticIpManagerApplication.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/dao/ElasticIpAllocator.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/dao/ElasticIpRangeRepo.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/dao/ElasticIpRepo.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/MacManagerApplication.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeMappingRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangePartitionRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacStateRepository.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/NodeManagerApplication.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/dao/NodeRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/PortManagerApplication.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/PrivateIpManagerApplication.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/repo/IpAddrRangeRepo.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/repo/IpAddrRepo.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/repo/VpcIpRangeRepo.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/RouteManagerApplication.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteWithSubnetMapperRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteWithVpcMapperRepository.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/SecurityGroupManagerApplication.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupBindingsRepository.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupRepository.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/SubnetApplication.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/dao/SubnetRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/VpcManagerApplication.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/SegmentRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/SegmentRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VlanRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VpcRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRepository.java
  web/src/main/java/com/futurewei/alcor/web/json/JsonHandlerConfiguration.java
Labels: enhancement

#348 [Vpc Mgr] Fix LIST Vpc Query Issue
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
Labels: bug

#345 [Data-Plane Mgr] Add Time Cost Estimation and Fixed Issue #344
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/GSController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/ClientOfDPMFailureException.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
Labels: bug

#351 [API GW] Ensure Thread-safe Date Format Strings
  lib/src/main/java/com/futurewei/alcor/common/entity/TokenEntity.java
  lib/src/main/java/com/futurewei/alcor/common/utils/ControllerUtil.java
  lib/src/main/java/com/futurewei/alcor/common/utils/DateUtil.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/client/KeystoneClient.java
Labels: bug

#350 [Performance] Add Time Cost Estimation for all Microservices
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/GSController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/MizarGoalStateServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/OVSGoalStateServiceImpl.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/controller/ElasticIpController.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/dao/ElasticIpAllocator.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/service/implement/ElasticIpRangeServiceImpl.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/service/implement/ElasticIpServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/controller/MacController.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeMappingRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangePartitionRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacStateRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacServiceImpl.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/controller/NodeController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteWithSubnetMapperRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteWithVpcMapperRepository.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/PortBindingSecurityGroupRepository.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupRepository.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/implement/SecurityGroupRuleServiceImpl.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/implement/SecurityGroupServiceImpl.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/dao/SubnetRepository.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/QuotaController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/SegmentRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/SegmentRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VlanRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VpcRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/VpcServiceImpl.java
Labels: enhancement, perf testing

#340 [Node Mgr] Support Bulk Node Registration and Fix Upload API
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/controller/NodeController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/NodeService.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeServiceImpl.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/utils/NodeManagerConstant.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/machine.json
  web/src/main/java/com/futurewei/alcor/web/entity/node/BulkNodeInfoJson.java
Labels: api, bug, feature

#356 [Microservice] Support Tenant_id Query
  lib/src/main/java/com/futurewei/alcor/common/entity/CustomerResource.java
Labels: bug

#347 [Integration] ElasticIP APIs Compatible with OpenStack
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthGwFilter.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/route/ElasticIPRouteConfiguration.java
  services/api_gateway/src/main/resources/application.properties
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/dao/ElasticIpAllocator.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/service/implement/ElasticIpServiceImpl.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/utils/ElasticIpControllerUtils.java
  services/elastic_ip_manager/src/test/java/com/futurewei/alcor/elasticipmanager/ElasticIpControllerTests.java
  services/elastic_ip_manager/src/test/java/com/futurewei/alcor/elasticipmanager/config/UnitTestConfig.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIp.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIpInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIpPortDetails.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpRequest.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpRequestWrapper.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpResponse.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpResponseWrapper.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpsWrapper.java
Labels: contract, enhancement

#358 [Design] Southbound Programming Workflow
  docs/modules/ROOT/images/southbound_prog_workflow_v1.png
  docs/modules/ROOT/images/southbound_prog_workflow_v2.png
  docs/modules/ROOT/pages/deploy_related/integration_keystone.adoc
  docs/modules/ROOT/pages/deploy_related/integration_nova.adoc
  docs/modules/ROOT/pages/high_level/southbound_workflow.adoc
  docs/modules/ROOT/workflows/southbound_prog_workflow_v1.puml
  docs/modules/ROOT/workflows/southbound_prog_workflow_v2.puml
Labels: documentation

#355 [Data-Plane Mgr] Support DHCP Programming for Port Creation
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
Labels: enhancement, feature

#357 [VPC Mgr] Fix VPC Creation Performance Issue
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/allocator/NetworkKeyAllocator.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/config/ConstantsConfig.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/config/UnitTestConfig.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/SegmentController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/entity/NetworkGRERange.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/entity/NetworkVlanRange.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/entity/NetworkVxlanRange.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/SegmentServiceImpl.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/VpcServiceImpl.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/SegmentService.java
  services/vpc_manager/src/test/java/com/futurewei/alcor/vpcmanager/SegmentControllerTests.java
Labels: perf testing

#317 [Mac Manager] Mac Range Selector
  docs/modules/ROOT/pages/mgmt_services/virtual_mac_manager.adoc
  kubernetes/services/mac_manager.yaml
  lib/src/main/java/com/futurewei/alcor/common/db/ICacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/MockIgniteServer.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/repo/ICacheRepositoryEx.java
  lib/src/main/java/com/futurewei/alcor/common/test/config/TestBeanFactoryPostProcessor.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/advice/MacControllerExceptionAdvice.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/controller/MacController.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeMappingRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacStateRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/api/IRangeMappingRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/MacAddressFullException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/MacAddressInvalidException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/MacAddressRetryLimitExceedException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/MacAddressUniquenessViolationException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/MacRangeDeleteNotAllowedException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/MacRangeInvalidException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/MacStateInvalidException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/pool/MacPoolApi.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/pool/impl/BitmapPoolImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/pool/impl/RandomMacPoolImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/MacService.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacManagerConstant.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacManagerRestPreconditionsUtil.java
  services/mac_manager/src/main/resources/application.properties
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/controller/MacControllerTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/mac/MacRangePartition.java
Labels: enhancement, feature

#352 [Rbac] Alcor Rbac Support
  docs/modules/ROOT/pages/high_level/rbac_design.adoc
  lib/src/main/java/com/futurewei/alcor/common/constants/CommonConstants.java
  lib/src/main/java/com/futurewei/alcor/common/entity/ActionRbacRule.java
  lib/src/main/java/com/futurewei/alcor/common/entity/FieldRbacRule.java
  lib/src/main/java/com/futurewei/alcor/common/entity/MethodType.java
  lib/src/main/java/com/futurewei/alcor/common/entity/RuleType.java
  lib/src/main/java/com/futurewei/alcor/common/entity/ServiceRbacRule.java
  lib/src/main/java/com/futurewei/alcor/common/exception/FieldPolicyNotAuthorizedException.java
  lib/src/main/java/com/futurewei/alcor/common/exception/ParseObjectException.java
  lib/src/main/java/com/futurewei/alcor/common/exception/PolicyNotAuthorizedException.java
  lib/src/main/java/com/futurewei/alcor/common/exception/PolicyResourceNotFoundException.java
  lib/src/main/java/com/futurewei/alcor/common/rbac/IgnoreRbacManager.java
  lib/src/main/java/com/futurewei/alcor/common/rbac/OwnerChecker.java
  lib/src/main/java/com/futurewei/alcor/common/rbac/RbacManagerConfiguration.java
  lib/src/main/java/com/futurewei/alcor/common/rbac/RbacManger.java
  lib/src/main/java/com/futurewei/alcor/common/rbac/StrictRbacManager.java
  lib/src/main/java/com/futurewei/alcor/common/utils/ControllerUtil.java
  lib/src/main/java/com/futurewei/alcor/common/utils/JsonUtil.java
  lib/src/main/resources/rbac_policy.json
  lib/src/test/java/com/futurewei/alcor/common/cache/entity/TestVpcEntity.java
  lib/src/test/java/com/futurewei/alcor/common/rbac/StrictRbacManagerTest.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/ElasticIpManagerApplication.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/controller/ElasticIpController.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/rbac/EipOwnerCheckerSupplier.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/service/implement/ElasticIpServiceImpl.java
  services/elastic_ip_manager/src/main/resources/application.properties
  services/elastic_ip_manager/src/main/resources/rbac_policy.json
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/PortManagerApplication.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rbac/PortOwnerCheckerSupplier.java
  services/port_manager/src/main/resources/application.properties
  services/port_manager/src/main/resources/rbac_policy.json
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/SecurityGroupManagerApplication.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupController.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupRuleController.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/rbac/SecurityGroupOwnerCheckerSupplier.java
  services/security_group_manager/src/main/resources/application.properties
  services/security_group_manager/src/main/resources/rbac_policy.json
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/SubnetApplication.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/rbac/SubnetOwnerCheckerSupplier.java
  services/subnet_manager/src/main/resources/application.properties
  services/subnet_manager/src/main/resources/rbac_policy.json
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/VpcManagerApplication.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/rbac/VpcOwnerCheckerSupplier.java
  services/vpc_manager/src/main/resources/application.properties
  services/vpc_manager/src/main/resources/rbac_policy.json
  web/src/main/java/com/futurewei/alcor/web/exception/NotAuthorizedException.java
  web/src/main/java/com/futurewei/alcor/web/exception/NotFoundException.java
  web/src/main/java/com/futurewei/alcor/web/rbac/aspect/OwnerCheckerSupplier.java
  web/src/main/java/com/futurewei/alcor/web/rbac/aspect/Rbac.java
  web/src/main/java/com/futurewei/alcor/web/rbac/aspect/RbacAspect.java
  web/src/main/java/com/futurewei/alcor/web/rbac/aspect/RbacConfiguration.java
Labels: feature

#367 [Deployment] Fix Rbac Config Load Error in K8s Deployment
  lib/src/main/java/com/futurewei/alcor/common/rbac/StrictRbacManager.java
Labels: deployment and upgrade, enhancement

#368 [Port Mgr] Fix Update Port Exception in DatabaseProcessor
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java
Labels: bug
