Repository futurewei-cloud/alcor, pull requests merged in 2020-05, with the labels that each got.

#183 [MAC manager] Improve API consistency and code refactor
  docs/design/images/services_macrange.png
  docs/design/images/services_macstate.png
  docs/design/mac_manager.adoc
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteConfiguration.java
  lib/src/main/java/com/futurewei/alcor/common/repo/ICacheRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/config/RedisConfiguration.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/controller/MacController.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacStateRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/redis/MacPoolRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/redis/MacRangeRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/redis/MacStateRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacRange.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacRangeJson.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacState.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacStateJson.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/InvalidMacRangeException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/RetryLimitExceedException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/MacService.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacRedisServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/redis/RedisMacRangePublisherServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/redis/RedisMacServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/redis/RedisPublisherServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacUtil.java
  services/mac_manager/src/main/resources/application.properties
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/AlcorMacManager/MacManagerApplicationTests.java
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/controller/MacControllerTest.java
Labels: Unit Test, enhancement

#186 Enable UTs in multiple services and fix CI issue
  .github/workflows/maven.yml
  docs/README.md
  scripts/test-prep.sh
  services/private_ip_manager/pom.xml
  services/private_ip_manager/src/main/resources/application.properties
  services/route_manager/pom.xml
  services/route_manager/src/main/resources/application.properties
  services/subnet_manager/pom.xml
  services/subnet_manager/src/main/resources/application.properties
  services/vpc_manager/pom.xml
  services/vpc_manager/src/main/resources/application.properties
Labels: Unit Test, bug, cicd

#184 Automatically generate Swagger documentation
  services/mac_manager/pom.xml
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/swagger/SwaggerConfig.java
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/swagger/SwaggerJsonTest.java
  services/private_ip_manager/pom.xml
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/swagger/SwaggerConfig.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/swagger/SwaggerJsonTest.java
  services/route_manager/pom.xml
  services/route_manager/src/test/java/com/futurewei/alcor/route/swagger/SwaggerConfig.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/swagger/SwaggerJsonTest.java
  services/subnet_manager/pom.xml
  services/subnet_manager/src/test/java/com/futurewei/alcor/subnet/swagger/SwaggerConfig.java
  services/subnet_manager/src/test/java/com/futurewei/alcor/subnet/swagger/SwaggerJsonTest.java
  services/vpc_manager/pom.xml
  services/vpc_manager/src/test/java/com/futurewei/alcor/vpcmanager/swagger/SwaggerConfig.java
  services/vpc_manager/src/test/java/com/futurewei/alcor/vpcmanager/swagger/SwaggerJsonTest.java
Labels: Feature, documentation

#187 [Alcor Tools] Set up a Swagger UI
  services/mac_manager/pom.xml
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/config/SwaggerConfig.java
  services/private_ip_manager/pom.xml
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/config/SwaggerConfig.java
  services/route_manager/pom.xml
  services/route_manager/src/main/java/com/futurewei/alcor/route/config/SwaggerConfig.java
  services/subnet_manager/pom.xml
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/config/SwaggerConfig.java
  services/vpc_manager/pom.xml
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/config/SwaggerConfig.java
Labels: UI

#188 [Mac manager] Support Ignite repository and update DB schema
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/config/RedisConfiguration.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/config/SwaggerConfig.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacPoolRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacStateRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/redis/MacPoolRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/redis/MacRangeRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/redis/MacStateRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacRange.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/redis/RedisMacRangePublisherServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/redis/RedisMacServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/redis/RedisPublisherServiceImpl.java
  services/mac_manager/src/main/resources/application.properties
Labels: enhancement

#189 [Microservice] Node Manager - Metadata Management
  lib/src/main/java/com/futurewei/alcor/common/utils/RestPreconditionsUtil.java
  pom.xml
  services/node_manager/.gitignore
  services/node_manager/.mvn/wrapper/MavenWrapperDownloader.java
  services/node_manager/.mvn/wrapper/maven-wrapper.jar
  services/node_manager/.mvn/wrapper/maven-wrapper.properties
  services/node_manager/Dockerfile
  services/node_manager/mvnw
  services/node_manager/mvnw.cmd
  services/node_manager/pom.xml
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/NodeManagerApplication.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/config/SwaggerConfig.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/controller/NodeController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/dao/NodeRepository.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/exception/InvalidDataException.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/exception/NodeRepositoryException.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/NodeService.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeServiceImpl.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/utils/NodeManagerConstant.java
  services/node_manager/src/main/resources/application.properties
  services/node_manager/src/main/resources/static/start.html
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/AlcorNodeManager/NodeManagerApplicationTests.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/machine.json
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/swagger/SwaggerJsonTest.java
  web/pom.xml
  web/src/main/java/com/futurewei/alcor/web/entity/NodeInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/NodeInfoJson.java
Labels: Feature

#196 [Port Manager] Fix bug where rest client is unachievable from SpringContextUtil
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
Labels: Feature, bug

#198 Standardize service pom file and remove unused dependencies
  lib/pom.xml
  pom.xml
  schema/pom.xml
  services/api_gateway/Dockerfile
  services/api_gateway/pom.xml
  services/mac_manager/Dockerfile
  services/mac_manager/pom.xml
  services/node_manager/Dockerfile
  services/node_manager/pom.xml
  services/port_manager/Dockerfile
  services/port_manager/pom.xml
  services/private_ip_manager/Dockerfile
  services/private_ip_manager/pom.xml
  services/route_manager/Dockerfile
  services/route_manager/pom.xml
  services/subnet_manager/Dockerfile
  services/subnet_manager/pom.xml
  services/vpc_manager/Dockerfile
  services/vpc_manager/pom.xml
  web/Dockerfile
  web/pom.xml
Labels: Build-related, enhancement

#202 [Document] Outline of Nova Integration and Migration from Neutron
  docs/design/deployment.adoc
  docs/design/images/vm_create.png
  docs/design/integration_nova.adoc
Labels: documentation

#201 [Node Manager] Junit test with MockIgniteServer
  services/node_manager/src/main/resources/application.properties
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
Labels: Unit Test

#210 [Document] Design Documentation Improvement with Antora
  README.md
  antora-playbook.yml
  docs/README.md
  docs/antora.yml
  docs/apis/api_completeness_analysis.adoc
  docs/apis/index.adoc
  docs/design/comm.adoc
  docs/design/images/services_macrange.png
  docs/design/mac_manager.adoc
  docs/design/table_of_content.adoc
  docs/modules/ROOT/images/alcor_architecture.PNG
  docs/modules/ROOT/images/alcor_build.JPG
  docs/modules/ROOT/images/controller.JPG
  docs/modules/ROOT/images/create_api_workflow.jpg
  docs/modules/ROOT/images/database.JPG
  docs/modules/ROOT/images/fast_path.GIF
  docs/modules/ROOT/images/monitoring_plane.GIF
  docs/modules/ROOT/images/network_type_gre.PNG
  docs/modules/ROOT/images/network_type_vlan.PNG
  docs/modules/ROOT/images/network_type_vxlan.PNG
  docs/modules/ROOT/images/private_ip_manager_bitset.png
  docs/modules/ROOT/images/private_ip_manager_hashmap.png
  docs/modules/ROOT/images/rescue_path.GIF
  docs/modules/ROOT/images/services_macrange.png
  docs/modules/ROOT/images/services_macstate.png
  docs/modules/ROOT/images/vm_create.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/comm_protocol/fast_path.adoc
  docs/modules/ROOT/pages/comm_protocol/goal_state_model.adoc
  docs/modules/ROOT/pages/comm_protocol/normal_path.adoc
  docs/modules/ROOT/pages/comm_protocol/rescue_path.adoc
  docs/modules/ROOT/pages/controller.adoc
  docs/modules/ROOT/pages/db_services/data_store.adoc
  docs/modules/ROOT/pages/deploy_related/deployment.adoc
  docs/modules/ROOT/pages/deploy_related/integration_nova.adoc
  docs/modules/ROOT/pages/high_level/high_level_design.adoc
  docs/modules/ROOT/pages/high_level/key_diff.adoc
  docs/modules/ROOT/pages/high_level/system_flow.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/infra_services/data_plane_manager.adoc
  docs/modules/ROOT/pages/infra_services/dataplane_abstraction.adoc
  docs/modules/ROOT/pages/infra_services/network_health_monitor.adoc
  docs/modules/ROOT/pages/mgmt_services/mgmt_services_overview.adoc
  docs/modules/ROOT/pages/mgmt_services/node_metadata_manager.adoc
  docs/modules/ROOT/pages/mgmt_services/private_ip_manager.adoc
  docs/modules/ROOT/pages/mgmt_services/subnet_manager.adoc
  docs/modules/ROOT/pages/mgmt_services/virtual_mac_manager.adoc
  docs/modules/ROOT/pages/mgmt_services/vpc_manager.adoc
  docs/modules/ROOT/pages/mq_services/message_queue_system.adoc
  docs/modules/ROOT/pages/sys_monitoring/controller_monitoring.adoc
  docs/modules/ROOT/pages/sys_monitoring/monitoring.adoc
  docs/modules/ROOT/pages/sys_monitoring/node_monitoring.adoc
  docs/modules/ROOT/workflows/template.puml
  docs/modules/ROOT/workflows/vm_create.puml
  docs/modules/ROOT/workflows/vpc_create.puml
Labels: documentation

#205 [Documentation] Migration Plan for OpenStack Users
  docs/modules/ROOT/images/neutron_migration_phase1.png
  docs/modules/ROOT/images/neutron_migration_phase2.png
  docs/modules/ROOT/images/neutron_migration_phase3.png
  docs/modules/ROOT/pages/deploy_related/deployment.adoc
Labels: documentation

#213 [Documentation] Fix Image Links, and Use Consistent Java Version
  README.md
  docs/modules/ROOT/pages/comm_protocol/fast_path.adoc
  docs/modules/ROOT/pages/comm_protocol/rescue_path.adoc
  docs/modules/ROOT/pages/controller.adoc
  docs/modules/ROOT/pages/db_services/data_store.adoc
  docs/modules/ROOT/pages/deploy_related/deployment.adoc
  docs/modules/ROOT/pages/deploy_related/integration_nova.adoc
  docs/modules/ROOT/pages/high_level/system_flow.adoc
  docs/modules/ROOT/pages/mgmt_services/private_ip_manager.adoc
  docs/modules/ROOT/pages/mgmt_services/virtual_mac_manager.adoc
  docs/modules/ROOT/pages/mgmt_services/vpc_manager.adoc
  docs/modules/ROOT/pages/sys_monitoring/monitoring.adoc
  pom.xml
  services/route_manager/pom.xml
  services/subnet_manager/pom.xml
  services/vpc_manager/pom.xml
Labels: bug, documentation

#215 [Documentation] Outline Elastic IP Manager Design
  docs/modules/ROOT/pages/mgmt_services/elastic_ip_manager.adoc
Labels: documentation

#212 [Schema Update] Add Version Support and Delta/Full Message Type
  schema/proto3/common.proto
  schema/proto3/dhcp.proto
  schema/proto3/goalstate.proto
  schema/proto3/goalstateprovisioner.proto
  schema/proto3/port.proto
  schema/proto3/securitygroup.proto
  schema/proto3/subnet.proto
  schema/proto3/vpc.proto
Labels: Feature
