Repository futurewei-cloud/alcor, pull requests merged in 2020-06, with the labels that each got.

#222 [Deployment] Deploying Resource Management Services with Kubernetes
  kubernetes/services/subnet_manager.yaml
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacManagerRestPreconditionsUtil.java
Labels: bug, build related

#235 [Build Fix] Reduce Controller Build Time from 45+ to <5 minutes
  services/mac_manager/src/main/resources/application.properties
  services/node_manager/src/main/resources/application.properties
  services/port_manager/src/main/resources/application.properties
  services/private_ip_manager/src/main/resources/application.properties
  services/route_manager/src/main/resources/application.properties
  services/subnet_manager/src/main/resources/application.properties
  services/vpc_manager/src/main/resources/application.properties
Labels: bug

#234 [Data Plane Manager] Add Internal Port Entity
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalPortEntityNB.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalSubnetEntityNB.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NeighborInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
Labels: contract

#219 [Api Gateway] Support Authentication with OpenStack KeyStone
  docs/modules/ROOT/images/keystone_filter_start_workflow.jpg
  docs/modules/ROOT/images/keystone_filter_workflow.jpg
  docs/modules/ROOT/pages/deploy_related/integration_keystone.adoc
  lib/src/main/java/com/futurewei/alcor/common/db/CacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ICacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisExpireCache.java
  lib/src/main/java/com/futurewei/alcor/common/entity/TokenEntity.java
  services/api_gateway/pom.xml
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/client/KeystoneClient.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthWebFilter.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneConfiguration.java
  services/api_gateway/src/main/resources/application.properties
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/AlcorApiGatewayApplicationTest.java
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthWebFilterTest.java
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneClientTest.java
Labels: feature, security

#247 [Code Coverage] Fix Code Coverage Script and Update CodeCov Badge
  README.md
  scripts/build_coverage.sh
Labels: bug, code coverage

#248 Microsevice Integration of Port Manager and Data-Plane Manager
  lib/src/main/java/com/futurewei/alcor/common/db/CacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteConfiguration.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisCacheFactory.java
  services/port_manager/pom.xml
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/PortManagerApplication.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/AllowAddressPairDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/DnsRecordDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/ExtraDhcpOptDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/FixedIpDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/PortDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/PortEntityDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/PortSecurityGroupDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/PortTagDao.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/dao/TransactionConfig.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/PortBindingHost.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/PortBindingRoute.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/PortNeighbors.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/DataPlaneManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/IpManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/NodeManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/RouteManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/SubnetManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/CreateNetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/DeleteNetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/NetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/UpdateNetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/GoalStateUtil.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/RestParameterValidator.java
  services/port_manager/src/main/resources/application.properties
  services/port_manager/src/main/resources/sql/allowed_address_pair.sql
  services/port_manager/src/main/resources/sql/dns_record.sql
  services/port_manager/src/main/resources/sql/extra_dhcp_opt.sql
  services/port_manager/src/main/resources/sql/fixed_ip.sql
  services/port_manager/src/main/resources/sql/port.sql
  services/port_manager/src/main/resources/sql/port_security_group.sql
  services/port_manager/src/main/resources/sql/port_tag.sql
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/ResourceBuilder.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalPortEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalSubnetEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NeighborInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/AllowAddressPair.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/DnsRecord.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/FixedIp.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntityOld.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/SubnetEntity.java
  web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
Labels: feature

#254 [Data-Plane Manager] Add New Response Class for DPM
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalDPMResultNB.java
Labels: contract

#257 [Database] Upgrade Ignite Version from 2.8.0 to 2.8.1
  kubernetes/db/ignite/ignite-deployment.yaml
  lib/pom.xml
  scripts/deploy.sh
  scripts/test-prep.sh
  services/node_manager/pom.xml
  services/private_ip_manager/pom.xml
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/controller/IpAddrControllerTest.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/util/IpAddressBuilder.java
Labels: dependencies

#249 [Node Manager] Add & Update Unit Test Cases
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/RestPreconditionsUtil.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/controller/NodeController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
Labels: unit test

#263 [Port Manager] Bug Fixes for Delete Ports, Duplicated Port-SG Binding
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/PortNeighbors.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/SecurityGroupManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java
Labels: bug

#269 RCA of Issue #264 with Fix of Port-SG Concurrent binding
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupBindingsRepository.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupRepository.java
  services/security_group_manager/src/test/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupTest.java
Labels: bug

#266 Upgrade Alcor Project to Use OpenJDK 11 LTS
  .github/workflows/maven.yml
  lib/pom.xml
  pom.xml
  schema/pom.xml
  services/api_gateway/pom.xml
  services/mac_manager/pom.xml
  services/node_manager/pom.xml
  services/port_manager/pom.xml
  services/private_ip_manager/pom.xml
  services/route_manager/pom.xml
  services/security_group_manager/pom.xml
  services/subnet_manager/pom.xml
  services/vpc_manager/pom.xml
  web/pom.xml
Labels: dependencies
