Repository futurewei-cloud/alcor, pull requests merged in 2020-10, with the labels that each got.

#396 [Contract] Add routers_internal to NetworkConfiguration Entity
  docs/modules/ROOT/pages/infra_services/data_plane_manager.adoc
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
Labels: contract

#394 [Data Plane Manager] UT Test Automation
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/constants/DPMAutoUnitTestConstant.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
Labels: unit test

#400 [Hotfix] Fix Update Port Issue to Handle Null BindingHostId
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java
Labels: bug

#401 [Performance] Increase Thread Pool Size to Improve Concurrency
  lib/src/main/java/com/futurewei/alcor/common/executor/ThreadPoolExecutorConfig.java
Labels: perf testing

#417 [Hotfix] Fix SecurityGroup Mgr and Route Mgr Issues
  scripts/build.sh
  services/port_manager/src/main/resources/application.properties
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupController.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/PortBindingSecurityGroupRepository.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/utils/RestParameterValidator.java
Labels: bug

#421 [Node Manager] Add host_dvr_mac field in NodeInfo
  web/src/main/java/com/futurewei/alcor/web/entity/NodeInfo.java
Labels: contract, enhancement, feature

#427 [Data Plane Mgr] Input Validation Module
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/BindingHostIPNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/HostIPNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/HostIdNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/NetworkConfigurationIsNull.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/OperationTypeNotValid.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortEntitiesIsNull.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortIPNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortIdNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/PortMacNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/ResourceTypeNotValid.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetIdNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetsNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/TunnelIdNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/VpcIdNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerValidationUtil.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/ParametersValidator.java
Labels: enhancement

#437 [Contract] Consolidate Host Related Entity Classes in a Package
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/controller/NodeController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/dao/NodeRepository.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/NodeService.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeServiceImpl.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/PortBindingHost.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NodeProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/NodeManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/FetchNodeRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/CreatePortTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/BulkNodeInfoJson.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/NodeInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/NodeInfoJson.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/NodeManagerConstant.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/NodesWebJson.java
  web/src/main/java/com/futurewei/alcor/web/restclient/NodeManagerRestClient.java
Labels: contract, dependencies

#438 [Compatibility] Make Subnet Entity OpenStack Compatible
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/utils/SubnetManagementUtil.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/AllocationPool.java
Labels: bug

#398 [Data Plane Mgr] UT Test Automation - Part II
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/UnitTestConfig.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/GSControllerTest.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/entity/UTIPInfo.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/entity/UTL3NeighborInfoMapping.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/entity/UTNeighborInfoDetail.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/entity/UTPortWithSubnetAndIPMapping.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/entity/UTSubnetInfo.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
Labels: unit test

#446 [Microservice] Port Mgr Support L3 Routing with Routing Rules
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/GetConnectedRouterException.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/VpcTunnelIdInvalid.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NetworkConfig.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/RouterProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/FetchRouterSubnetsRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/config/UnitTestConfig.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/config/ConstantsConfig.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/ConnectedSubnetsWebResponse.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/InternalRouterInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/Router.java
Labels: enhancement, feature

#451 [Mac Manager] Standardize Mac Addresses Format
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacUtils.java
  services/mac_manager/src/main/resources/application.properties
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/controller/MacControllerTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/mac/MacAddress.java
Labels: bug

#454 [Port Mgr] Fix L3 Routing Issues for Unassociated Subnets
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
Labels: bug

#456 [Data Plane Mgr] Fix Config Autowired Issue Causing Start Failure
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DataPlaneController.java
Labels: bug
