Repository futurewei-cloud/alcor, pull requests merged in 2020-12, with the labels that each got.

#429 [Documentation] Subnet Mgr Redesign with Routing Rule Update
  docs/modules/ROOT/images/route_manager_subnet_routing_rules_update_6.PNG
  docs/modules/ROOT/images/subnet_manager_architecture.PNG
  docs/modules/ROOT/images/subnet_manager_gatewayport_update.PNG
  docs/modules/ROOT/images/subnet_manager_keyflow.PNG
  docs/modules/ROOT/images/subnet_manager_mapping_cache.PNG
  docs/modules/ROOT/images/subnet_manager_routing_rules_update_architecture.PNG
  docs/modules/ROOT/images/subnet_manager_sidecar_cache_cluster.PNG
  docs/modules/ROOT/images/subnet_manager_subnet_entity.PNG
  docs/modules/ROOT/images/subnet_manager_subnet_ports_mapping.PNG
  docs/modules/ROOT/images/subnet_manager_subnetports_and_other_contracts.PNG
  docs/modules/ROOT/pages/mgmt_services/subnet_manager.adoc
Labels: documentation, feature

#486 [Data-Plane Mgr] Add Local Cache Support to DPM
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCacheImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/SubnetPortsCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/DataPlaneClient.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/kafka/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DpmController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/GSController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/DpmService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DhcpService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/ResourceService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/RouterService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SecurityGroupService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/VpcService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/mizar/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/mizar/MizarGoalStateServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/OVSGoalStateServiceImpl.java
  services/data_plane_manager/src/main/resources/application.properties
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/DpmTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalDPMResult.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/v2/NetworkConfiguration.java
Labels: enhancement, feature

#493 [Documentation] Update Route Manager Design Doc
  docs/README.md
  docs/modules/ROOT/images/route_manager_internalrouterinfo.PNG
  docs/modules/ROOT/images/route_manager_l3_neighbors_update_5.PNG
  docs/modules/ROOT/images/route_manager_routerinfo_contract.PNG
  docs/modules/ROOT/images/route_manager_routing_rule_update_6.PNG
  docs/modules/ROOT/pages/mgmt_services/route_manager.adoc
Labels: documentation

#485 [Build Tool] Add Script to Build Docker Image for Services
  kubernetes/services/only-build-docker.sh
Labels: build related, enhancement

#501 [Hotfix] Fix Issue that gRPC Client and Pulsar Client Can't Coexist
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/DataPlaneManager.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
Labels: bug

#502 [Enhancement] Verify Project Id for DB query
  web/src/main/java/com/futurewei/alcor/web/rbac/aspect/RbacAspect.java
Labels: enhancement

#503 [Dependency] Upgrade Ignite to 2.9.0
  legacy/pom.xml
  lib/pom.xml
Labels: dependencies, deployment and upgrade

#504 [Hotfix] Short-term Solution to GW Port Issues
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/FixedIpsProcessor.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterToSubnetServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/utils/RouteManagerUtil.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/test/java/com/futurewei/alcor/subnet/SubnetControllerTests.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/SubnetEntity.java
Labels: bug

#512 [Microservice] Move forward to DPM v2.0 APIs
  kubernetes/services/port_manager.yaml
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCacheImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/DataPlaneClient.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/kafka/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/config/TestConfig.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/DpmTest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NeighborProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NetworkConfig.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/DataPlaneManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/CreateNetworkConfigRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/DeleteNetworkConfigRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/FetchPortNeighborRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/UpdateNetworkConfigRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/CreateNetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/DeleteNetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/NetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/UpdateNetworkConfigRollback.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/RestParameterValidator.java
  services/port_manager/src/main/resources/application.properties
  web/src/main/java/com/futurewei/alcor/web/entity/route/RouterUpdateInfo.java
  web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
Labels: enhancement, feature

#515 Correctly Handle Fields with Null Value for JSON Deserialization
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/SubnetPortIds.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/FixedIpsProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/MacProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NeighborProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NodeProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/RouterProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/SecurityGroupProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/VpcProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortService.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/ArrayUtil.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/CreatePortTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/GetPortTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
  web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIpInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
Labels: bug

#514 [Bug Fix] Fix Issue #455 and Issue #274
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteEntryRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteTableRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouterExtraAttributeRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouterRepository.java
  web/src/main/java/com/futurewei/alcor/web/entity/vpc/VpcEntity.java
Labels: bug

#519 Make changes according to the suggestions of the review
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
Labels: enhancement

#521 One port supports multiple neighbors && Fix the failure to update port
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/FixedIpsProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/NeighborRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/SubnetPortsRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
Labels: enhancement

#517 [Documentation] Gateway Manager Design doc
  docs/modules/ROOT/images/gateway_manager_data_schema.PNG
  docs/modules/ROOT/images/gateway_manager_service_architecture.PNG
  docs/modules/ROOT/images/gateway_manager_vpc_zetagateway_creation.PNG
  docs/modules/ROOT/images/gateway_manager_zeta_port_creation.PNG
  docs/modules/ROOT/pages/mgmt_services/gateway_manager.adoc
Labels: documentation

#525 []Fix the problem of failed to create a port
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
Labels: bug

#528 [Deployment] Update Ignite XML Configuration
  kubernetes/services/ignite_config.xml
  kubernetes/services/ignite_ip_config.xml
  kubernetes/services/ignite_mac_config.xml
  kubernetes/services/ignite_port_config.xml
Labels: deployment and upgrade
