Repository futurewei-cloud/alcor, pull requests merged in 2020-02, with the labels that each got.

#118 Build and deploy scripts support Mac OS X
  .gitignore
  scripts/build.sh
  scripts/deploy.sh
  src/README.md
Labels: Build-related

#120 Change default size of log file to 10 MB
  src/com/futurewei/alcor/controller/logging/FileLogger.java
Labels: bug

#121 update onebox test script based on latest implementation
  config/machine.json
Labels: Environment Setup

#123 Add API document v0.1
  docs/apis/api.adoc
  docs/apis/index.adoc
  pom.xml
  test/com/futurewei/alcor/controller/web/DebugControllerTest.java
  timestamp.log
Labels: documentation

#124 Update README with google group
  README.md
Labels: documentation
