Repository futurewei-cloud/alcor, pull requests merged in 2020-07, with the labels that each got.

#271 [Port Manager] Add some UTs to Cover PortRepository Interfaces
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/CreatePortTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/DeletePortTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/GetPortTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/repo/PortRepositoryTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
Labels: unit test

#272 [Private IP Manager] Add UTs to Cover IpAddrRangeRepo interfaces
  lib/src/main/java/com/futurewei/alcor/common/db/MockCache.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/repo/IpAddrRangeRepo.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/config/UnitTestConfig.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/controller/IpAddrControllerTest.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/repo/IpAddrTest.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/repo/IpRangeTest.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/util/IpAddressBuilder.java
Labels: unit test

#253 [Alcor Integration]Port CURD - Bug Fix and New Route Manager APIs
  docs/modules/ROOT/pages/comm_protocol/fast_path.adoc
  docs/modules/ROOT/pages/comm_protocol/rescue_path.adoc
  docs/modules/ROOT/pages/db_services/data_store.adoc
  docs/modules/ROOT/pages/deploy_related/deployment.adoc
  docs/modules/ROOT/pages/high_level/system_flow.adoc
  docs/modules/ROOT/pages/mgmt_services/private_ip_manager.adoc
  docs/modules/ROOT/pages/mgmt_services/security_group_manager.adoc
  kubernetes/services/sg_manager.yaml
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/RouteManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java
  services/port_manager/src/main/resources/application.properties
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouteController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteWithSubnetMapperRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteWithVpcMapperRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouteDatabaseServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouteWithSubnetMapperServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouteWithVpcMapperServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouteDatabaseService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouteWithSubnetMapperService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouteWithVpcMapperService.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/RouteControllerTests.java
  services/security_group_manager/src/main/resources/application.properties
  services/vpc_manager/pom.xml
  web/pom.xml
  web/src/main/java/com/futurewei/alcor/web/entity/route/RouteWithSubnetEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/RoutesWebJson.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/SubnetToRouteMapper.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/VpcToRouteMapper.java
  web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/RouteManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/SecurityGroupManagerRestClient.java
Labels: api, bug, enhancement

#276 Add performance statistics for port manager
  lib/pom.xml
  lib/src/main/java/com/futurewei/alcor/common/stats/DurationStatistics.java
  lib/src/main/java/com/futurewei/alcor/common/stats/StatisticsAspect.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/IpManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/MacManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/NodeManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/RouteManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/SecurityGroupManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/SubnetManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/VpcManagerRestClient.java
Labels: perf testing

#290 [K8s] Kubernetes yaml files update
  kubernetes/services/api-gateway.yaml
  kubernetes/services/ignite_alcor.yaml
  kubernetes/services/ip_manager.yaml
  kubernetes/services/mac_manager.yaml
  kubernetes/services/node_manager.yaml
  kubernetes/services/port_manager.yaml
  kubernetes/services/route_manager.yaml
  kubernetes/services/sg_manager.yaml
  kubernetes/services/subnet_manager.yaml
  kubernetes/services/vpc_manager.yaml
Labels: deployment and upgrade

#291 [K8s] Kubernetes yaml file update (second version)
  kubernetes/services/dpm_manager.yaml
  kubernetes/services/port_manager.yaml
  kubernetes/services/private_ip_manager.yaml
  kubernetes/services/redis.yaml
  kubernetes/services/redis_mac.yaml
  kubernetes/services/redis_route.yaml
  kubernetes/services/redis_subnet.yaml
  services/data_plane_manager/Dockerfile
Labels: deployment and upgrade

#293 [Hotfix] Fix Multiple Ignite Client Issues, Reorg Conf Files
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteConfiguration.java
  services/api_gateway/Dockerfile
  services/api_gateway/src/main/resources/application.properties
  services/data_plane_manager/Dockerfile
  services/data_plane_manager/pom.xml
  services/data_plane_manager/src/main/resources/application.properties
  services/elastic_ip_manager/Dockerfile
  services/elastic_ip_manager/src/main/resources/application.properties
  services/mac_manager/Dockerfile
  services/mac_manager/src/main/resources/application.properties
  services/node_manager/Dockerfile
  services/node_manager/src/main/resources/application.properties
  services/port_manager/Dockerfile
  services/port_manager/pom.xml
  services/port_manager/src/main/resources/application.properties
  services/private_ip_manager/Dockerfile
  services/private_ip_manager/src/main/resources/application.properties
  services/route_manager/Dockerfile
  services/route_manager/src/main/java/com/futurewei/alcor/route/RouteManagerApplication.java
  services/route_manager/src/main/resources/application.properties
  services/route_manager/src/test/java/com/futurewei/alcor/route/RouteManagerApplicationTests.java
  services/security_group_manager/Dockerfile
  services/security_group_manager/src/main/resources/application.properties
  services/subnet_manager/Dockerfile
  services/subnet_manager/src/main/resources/application.properties
  services/vpc_manager/Dockerfile
  services/vpc_manager/src/main/resources/application.properties
Labels: bug, deployment and upgrade

#294 [Hotfix] Fix Multiple Ignite Client Errors
  lib/src/main/java/com/futurewei/alcor/common/db/DistributedLockFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ICacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/IDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientDistributedLockFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteConfiguration.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteDistributedLockFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisConfiguration.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisDistributedLockFactory.java
  lib/src/main/java/com/futurewei/alcor/common/test/config/TestBeanFactoryPostProcessor.java
  lib/src/main/java/com/futurewei/alcor/common/test/config/TestBeanPostProcessor.java
Labels: bug

#300 [Subnet Manager] Fix Ip Fallback Issue
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
Labels: bug

#297 [Ignite] Set Ignite Thin Client as the Default Client
  services/api_gateway/src/main/resources/application.properties
  services/elastic_ip_manager/src/main/resources/application.properties
  services/mac_manager/src/main/resources/application.properties
  services/node_manager/src/main/resources/application.properties
  services/port_manager/src/main/resources/application.properties
  services/private_ip_manager/src/main/resources/application.properties
  services/route_manager/src/main/resources/application.properties
  services/security_group_manager/src/main/resources/application.properties
  services/subnet_manager/src/main/resources/application.properties
  services/vpc_manager/src/main/resources/application.properties
Labels: deployment and upgrade

#292 [Mac Manager] Optimize Mac Allocation Algorithm to Cut Latency
  lib/src/main/java/com/futurewei/alcor/common/db/ICache.java
  lib/src/main/java/com/futurewei/alcor/common/db/IDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/MockCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientDbCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteDbCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisExpireCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/repo/ICacheRepositoryEx.java
  services/mac_manager/pom.xml
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/controller/MacController.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacPoolRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeMappingRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangePartitionRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacStateRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/api/IRangeMappingRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/pool/MacPoolApi.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/pool/impl/BitmapPoolImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/pool/impl/RandomMacPoolImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/MacService.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacManagerRestPreconditionsUtil.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacUtils.java
  services/mac_manager/src/main/resources/application.properties
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/controller/MacControllerTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/mac/MacAllocate.java
  web/src/main/java/com/futurewei/alcor/web/entity/mac/MacRange.java
  web/src/main/java/com/futurewei/alcor/web/entity/mac/MacRangePartition.java
  web/src/main/java/com/futurewei/alcor/web/entity/mac/MacState.java
  web/src/main/java/com/futurewei/alcor/web/entity/mac/MacStateBulkJson.java
Labels: enhancement, feature, refactor

#308 [Common Lib] Fix Distribution Lock Name Bug
  lib/src/main/java/com/futurewei/alcor/common/db/IDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteDistributedLock.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisDistributedLock.java
Labels: bug

#307 [Microservice API] VPC Mgr and Subnet Mgr Issue Fix
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/config/ConstantsConfig.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/config/UnitTestConfig.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/exception/GatewayIpUnsupported.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/exception/SubnetIdIsNull.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/utils/SubnetManagementUtil.java
  services/subnet_manager/src/test/java/com/futurewei/alcor/subnet/SubnetControllerTests.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/config/ConstantsConfig.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/VpcServiceImpl.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/SegmentService.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/VpcService.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/utils/VpcManagementUtil.java
  services/vpc_manager/src/test/java/com/futurewei/alcor/vpcmanager/VpcControllerTests.java
  web/src/main/java/com/futurewei/alcor/web/entity/vpc/VpcEntity.java
Labels: bug

#311 [Hotfix] Add missing configuration annotation to EIP RestClient
  web/src/main/java/com/futurewei/alcor/web/restclient/ElasticIpManagerRestClient.java
Labels: bug

#310 [Hotfix] Fix resource_request Field in PortEntity
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/ResourceRequest.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/Resources.java
Labels: api, bug

#313 [UT Fix] Stabilize SwaggerJsonTest UT
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/MockIgniteServer.java
  lib/src/main/java/com/futurewei/alcor/common/utils/SpringContextUtil.java
Labels: bug, cicd, unit test

#325 [Ignite Deployment] Support Multi-Instances Multi-Node Deployment in K8s
  kubernetes/services/ignite_alcor.yaml
  kubernetes/services/ignite_config.xml
  lib/Dockerfile
Labels: bug

#321 [Spring Config] Remove Redis Health Check to Avoid Start Service Error
  services/elastic_ip_manager/src/main/resources/application.properties
  services/mac_manager/src/main/resources/application.properties
  services/node_manager/src/main/resources/application.properties
  services/port_manager/src/main/resources/application.properties
  services/private_ip_manager/src/main/resources/application.properties
  services/route_manager/src/main/resources/application.properties
  services/security_group_manager/src/main/resources/application.properties
  services/subnet_manager/src/main/resources/application.properties
  services/vpc_manager/src/main/resources/application.properties
Labels: enhancement

#316 [Microservice API] Make PortEntity Fully Compatible With Neutron
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/Config.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/GSController.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/UpdatePortTest.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalDPMResultList.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalSubnetEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/BindingProfile.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/BindingVifDetails.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/LocalLinkInformation.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/SubnetEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/vpc/VpcEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/vpc/VpcWebRequestObject.java
Labels: bug

#326 Node Mgr Supports Param Query, Port Mgr Binds with Machine Name
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/controller/NodeController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/NodeService.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeServiceImpl.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/MultipleNodeInfosHaveSameNodeName.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/NodeManagerProxy.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/config/UnitTestConfig.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/CreatePortTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  web/src/main/java/com/futurewei/alcor/web/restclient/NodeManagerRestClient.java
Labels: enhancement, feature

#327 [Logging] Enhance API GW Logging
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/client/KeystoneClient.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthGwFilter.java
Labels: logging

#306 [Deployment] Alcor Onebox Setup for Development and Deployment
  scripts/Dockerfile
  scripts/json/cp1b.json
  scripts/json/csn.json
  scripts/json/cvpc.json
  scripts/json/node.json
  scripts/json/sg.json
  scripts/restart.sh
  scripts/startall.sh
  scripts/test1.sh
Labels: environment setup

#331 [Data-Plane Mgr] Fix Port Name Null Issue
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
Labels: bug

#333 [API GW] Differentiate Handling of Tokens in Admin & User Role
  lib/src/main/java/com/futurewei/alcor/common/entity/TokenEntity.java
  lib/src/main/java/com/futurewei/alcor/common/utils/ControllerUtil.java
  lib/src/main/java/com/futurewei/alcor/common/utils/DateUtil.java
  lib/src/main/java/com/futurewei/alcor/common/utils/JsonUtil.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/client/KeystoneClient.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthGwFilter.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthWebFilter.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneConfiguration.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/proxies/SubnetManagerServiceProxy.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/proxies/VpcManagerServiceProxy.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/subnet/SubnetWebConfiguration.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/subnet/SubnetWebDestinations.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/subnet/SubnetWebHandlers.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/vpc/VpcWebConfiguration.java
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/vpc/VpcWebHandlers.java
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/AlcorApiGatewayApplicationTest.java
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthGwFilterTest.java
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthWebFilterTest.java
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneClientTest.java
  services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/controller/ElasticIpController.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupController.java
  services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupRuleController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
  services/vpc_manager/src/test/java/com/futurewei/alcor/vpcmanager/VpcControllerTests.java
Labels: enhancement, feature

#336 [Schema] Add Pending Operation Status for Port Operation
  schema/proto3/common.proto
Labels: schema

#334 [Subnet Mgr] Add validation of CIDR overlap for Subnet Creation/Update
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/exception/CidrNotWithinNetworkCidr.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/exception/CidrOverlapWithOtherSubnets.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/utils/SubnetManagementUtil.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/QuotaController.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/SubnetEntity.java
Labels: bug, enhancement
