Repository futurewei-cloud/alcor, pull requests merged in 2020-04, with the labels that each got.

#146 Update build scripts to support microservices build on Linux/MacOsX/Windows
  scripts/build.ps1
  scripts/build.sh
Labels: Build-related

#156 [Documentation] New controller and agent design docs
  README.md
  docs/visionary_design/controller.adoc
  docs/visionary_design/controller_monitoring.adoc
  docs/visionary_design/data_store.adoc
  docs/visionary_design/dataplane_abstraction.adoc
  docs/visionary_design/deployment.adoc
  docs/visionary_design/fast_path.adoc
  docs/visionary_design/high_level_design.adoc
  docs/visionary_design/images/controller.JPG
  docs/visionary_design/images/create_api_workflow.jpg
  docs/visionary_design/images/fast_path.GIF
  docs/visionary_design/images/monitoring_plane.GIF
  docs/visionary_design/images/rescue_path.GIF
  docs/visionary_design/images/services_macrange.png
  docs/visionary_design/images/services_macstate.png
  docs/visionary_design/key_diff.adoc
  docs/visionary_design/mac_manager.adoc
  docs/visionary_design/monitoring.adoc
  docs/visionary_design/node_monitoring.adoc
  docs/visionary_design/rescue_path.adoc
  docs/visionary_design/system_flow.adoc
  docs/visionary_design/table_of_content.adoc
  src/README.md
Labels: documentation

#158 Update maven CI workflow to support microservices
  .github/workflows/maven.yml
Labels: Build-related

#153 [Database] Add UTs, deployment script and k8s yaml for ignite
  config/ignite-config.xml
  kubernetes/db/ignite/ignite-cluster-role-binding.yaml
  kubernetes/db/ignite/ignite-cluster-role.yaml
  kubernetes/db/ignite/ignite-deployment.yaml
  kubernetes/db/ignite/ignite-namespace.yaml
  kubernetes/db/ignite/ignite-service-account.yaml
  kubernetes/db/ignite/ignite-service.yaml
  kubernetes/db/redis/redis-deployment.yaml
  kubernetes/db/redis/redis-service.yaml
  scripts/deploy.sh
  src/com/futurewei/alcor/controller/db/CacheFactory.java
  test/com/futurewei/alcor/controller/db/CacheTest.java
  test/com/futurewei/alcor/controller/db/MultiClientTest1.java
  test/com/futurewei/alcor/controller/db/MultiClientTest2.java
Labels: Build-related, Unit Test

#147 [Microservices] MAC address manager
  .github/workflows/maven.yml
  docs/visionary_design/images/services_macrange.png
  docs/visionary_design/mac_manager.adoc
  services/mac_manager/.gitignore
  services/mac_manager/.mvn/wrapper/MavenWrapperDownloader.java
  services/mac_manager/.mvn/wrapper/maven-wrapper.jar
  services/mac_manager/.mvn/wrapper/maven-wrapper.properties
  services/mac_manager/mvnw
  services/mac_manager/mvnw.cmd
  services/mac_manager/pom.xml
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/MacManagerApplication.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/config/RedisConfiguration.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/controller/MacController.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacPoolRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRangeRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRedisRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/dao/MacRepository.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacAddress.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacRange.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacRangeJson.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacState.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/entity/MacStateJson.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/exception/UniquenessViolationException.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/MacService.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacRedisServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/RedisMacRangePublisherServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/RedisPublisherServiceImpl.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacUtil.java
  services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/RestPreconditionsUtil.java
  services/mac_manager/src/main/resources/application.properties
  services/mac_manager/src/main/resources/static/start.html
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/AlcorMacManager/MacManagerApplicationTests.java
  services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/controller/MacControllerTest.java
Labels: Feature

#164 [Micro-service] Private IP manager
  docs/visionary_design/images/private_ip_manager_bitset.png
  docs/visionary_design/images/private_ip_manager_hashmap.png
  docs/visionary_design/private_ip_manager.adoc
  docs/visionary_design/table_of_content.adoc
  lib/src/main/java/com/futurewei/alcor/common/db/CacheException.java
  lib/src/main/java/com/futurewei/alcor/common/db/CacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ICache.java
  lib/src/main/java/com/futurewei/alcor/common/db/Transaction.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteConfiguration.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteTransaction.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisConfiguration.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisTransaction.java
  services/private_ip_manager/.gitignore
  services/private_ip_manager/.mvn/wrapper/MavenWrapperDownloader.java
  services/private_ip_manager/.mvn/wrapper/maven-wrapper.jar
  services/private_ip_manager/.mvn/wrapper/maven-wrapper.properties
  services/private_ip_manager/pom.xml
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/PrivateIpManagerApplication.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/allocator/IpAddrAllocator.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/allocator/Ipv4AddrAllocator.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/allocator/Ipv6AddrAllocator.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/controller/IpAddrController.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpAddrAlloc.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpAddrRange.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpAddrRangeRequest.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpAddrRequest.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpAddrRequestBulk.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpAddrState.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpVersion.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/InternalDbOperationException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrAllocNotFoundException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrInvalidException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrNotEnoughException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrNotFoundException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrRangeExistException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrRangeInvalidException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrRangeNotFoundException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpAddrStateInvalidException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpRangeIdInvalidException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpRangeNotFoundException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/IpVersionInvalidException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/exception/SubnetIdInvalidException.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/repo/IpAddrRangeRepo.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/repo/IpAddrRepo.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/service/IpAddrService.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/service/implement/IpAddrServiceImpl.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/utils/Ipv4AddrUtil.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/utils/Ipv6AddrUtil.java
  services/private_ip_manager/src/main/resources/application.properties
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/PrivateIpManagerApplicationTests.java
  services/private_ip_manager/src/test/java/com/futurewei/alcor/privateipmanager/controller/IpAddrControllerTest.java
Labels: Feature, P0

#171 Onboard Ignite to VPC Manager and Route Manager
  lib/src/main/java/com/futurewei/alcor/common/db/repo/ICacheRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/config/RedisConfiguration.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouteController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteRedisRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RedisPublisher.java
  services/route_manager/src/main/resources/application.properties
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/config/RedisConfiguration.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/DebugController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/DebugVpcController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VpcRedisRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VpcRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/RedisPublisher.java
  services/vpc_manager/src/main/resources/application.properties
Labels: enhancement

#173 Fix script permission issue causing CI failure
  scripts/build.sh
  scripts/deploy.sh
  scripts/deployK8sClusterService.sh
  scripts/sampleEP2.sh
  scripts/sampleEP3.sh
  scripts/sampleVpcTest.sh
Labels: bug

#179 [CI/CD] Disable docker CI workflow
  .github/workflows/dockerimage.yml
Labels: bug, cicd
