Repository futurewei-cloud/alcor, pull requests merged in 2020-09, with the labels that each got.

#378 [DPM] Fix Hashcode Bug Causing 10s Latency for 10K Neighbors
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NeighborInfo.java
Labels: bug, perf testing

#381 [DPM/ACA Schema] Update Routing_rules and Add RoutingRuleExtraInfo Message
  docs/modules/ROOT/images/router_e2e_workflow.png
  docs/modules/ROOT/workflows/router_e2e_workflow.puml
  schema/proto3/neighbor.proto
  schema/proto3/router.proto
Labels: contract

#382 [Documentation] Route Manager Design doc
  docs/modules/ROOT/images/route_manager_data_schemas.PNG
  docs/modules/ROOT/images/route_manager_highlevel_design.PNG
  docs/modules/ROOT/images/route_manager_l3_neighbors_update_4.PNG
  docs/modules/ROOT/images/route_manager_l3_neighbors_update_5.PNG
  docs/modules/ROOT/images/route_manager_sequence_diagrams.puml
  docs/modules/ROOT/images/route_manager_service_architecture.PNG
  docs/modules/ROOT/images/route_manager_subnet_routing_rules_update_6.PNG
  docs/modules/ROOT/images/router_three_layers_strcuture.PNG
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/mgmt_services/route_manager.adoc
Labels: documentation

#373 [New Admin API] Pre-Create VNI Ranges (VxLan/GRE)
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/SegmentController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/entity/NetworkGRERange.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/entity/NetworkVxlanRange.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/SegmentServiceImpl.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/SegmentService.java
Labels: enhancement, perf testing

#383 [New APIs] API GW supports Neutron-Compatible Routers APIs
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/route/RouterRouteConfiguration.java
  services/api_gateway/src/main/resources/application.properties
Labels: api

#385 [Route-Manager] Fix Neutron Router Issues
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/utils/RouteManagerUtil.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/NeutronRoutersWebJson.java
Labels: bug

#387 [Deployment] Fix Quota Manager Deployment Issue for K8s
  services/quota_manager/pom.xml
  services/quota_manager/src/main/java/com/futurewei/alcor/quota/QuotaManagerApplication.java
Labels: bug

#389 [DPM] Refactor UTs
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/UnitTestConfig.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/GoalStateManagerTest.java
Labels: enhancement

#391 [Quota Manager] Fix k8s Deployment Issues
  kubernetes/services/api-gateway.yaml
  kubernetes/services/quota_manager.yaml
  services/quota_manager/Dockerfile
Labels: deployment and upgrade

#366 [Port Manager] Support L2 and L3 Type Neighbors
  services/data_plane_manager/pom.xml
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/DataPlaneClient.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/kafka/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/TopicManager.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DataPlaneController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/HostGoalState.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/NeighborInfoNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SecurityGroupNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SubnetEntityNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/UnknownResourceType.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/VpcEntityNotFound.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/DataPlaneService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/mizar/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/GetConnectedSubnetException.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/OperationTypeInvalid.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/SubnetIdInvalid.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/UnsupportedException.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/VpcIdInvalid.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/AbstractProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/AfterProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/FixedIpsProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/MacProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NeighborProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NetworkConfig.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NodeProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/ProcessorManager.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/RouterProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/SecurityGroupProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/VpcProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/FetchRouterSubnetsRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortService.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/RestParameterValidator.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/config/UnitTestConfig.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/UpdateL3NeighborTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalPortEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NeighborEntry.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NeighborInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/RouterUpdateInfo.java
  web/src/main/java/com/futurewei/alcor/web/restclient/RouterManagerRestClient.java
Labels: feature

#392 [Hotfix] Disable Pulsar Client and Fix gRPC Client
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
Labels: bug

#393 [Contract] Router Internal Config and Related Entity Classes
  lib/src/main/java/com/futurewei/alcor/common/enumClass/MessageType.java
  lib/src/main/java/com/futurewei/alcor/common/enumClass/OperationType.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/InternalRouterConfiguration.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/InternalRouterInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/InternalRoutingRule.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/InternalRoutingRuleExtraInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/InternalSubnetRoutingTable.java
Labels: contract
