Repository futurewei-cloud/alcor, pull requests merged in 2021-09, with the labels that each got.

#687 [CI/CD] Automate building ACA from jenkins jobs
  scripts/busybox-ping-test/build_aca.sh
  scripts/busybox-ping-test/remote_aca_build.sh
Labels: cicd

#685 Fix race condition for subnet, port and ip APIs
  kubernetes/services/ignite_ip_config.xml
  kubernetes/services/ignite_port_config.xml
  lib/src/main/java/com/futurewei/alcor/common/db/CacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ICacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientDbCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteDbCache.java
  lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisCacheFactory.java
  lib/src/main/java/com/futurewei/alcor/common/db/repo/ICacheRepository.java
  lib/src/main/java/com/futurewei/alcor/common/utils/CommonUtil.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/NeighborRepository.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/entity/IpAddrRange.java
  services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/repo/IpAddrRangeRepo.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/IVpcRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/SegmentRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/SegmentRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VpcRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/NetworkIPAvailabilityServiceImpl.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/VpcDatabaseServiceImpl.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/VpcServiceImpl.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/NetworkIPAvailabilityService.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/VpcDatabaseService.java
  web/src/main/java/com/futurewei/alcor/web/entity/vpc/VpcEntity.java
Labels: bug, perf testing

#688 [Data Plane Mgr] Fix issues from test scenario 4.5
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterToDPMServiceImpl.java
Labels: bug
