Repository futurewei-cloud/alcor, pull requests merged in 2021-01, with the labels that each got.

#529 [Deployment] Comprehensive Update for K8s Yaml and Scripts
  kubernetes/services/api-gateway.yaml
  kubernetes/services/deleteYaml.sh
  kubernetes/services/dpm_manager.yaml
  kubernetes/services/elastic_ip_manager.yaml
  kubernetes/services/ignite_alcor.yaml
  kubernetes/services/ignite_alcor_ip.yaml
  kubernetes/services/ignite_alcor_mac.yaml
  kubernetes/services/ignite_alcor_port.yaml
  kubernetes/services/mac_manager.yaml
  kubernetes/services/node_manager.yaml
  kubernetes/services/port_manager.yaml
  kubernetes/services/private_ip_manager.yaml
  kubernetes/services/quota_manager.yaml
  kubernetes/services/route_manager.yaml
  kubernetes/services/sg_manager.yaml
  kubernetes/services/subnet_manager.yaml
  kubernetes/services/vpc_manager.yaml
  lib/pom.xml
  scripts/basicTest.sh
  scripts/build.sh
  scripts/json/createNode.json
  scripts/json/createPort.json
  scripts/json/createSecurityGroup.json
  scripts/json/createSubnet.json
  scripts/json/createVPC.json
  services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/AlcorApiGatewayApplicationTest.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouteController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/test/java/com/futurewei/alcor/subnet/SubnetControllerTests.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/SubnetEntity.java
Labels: dependencies, deployment and upgrade

#534 [Fundamental] Fix Java Version in Common Lib
  lib/pom.xml
Labels: bug

#536 Fix Subnet Deletion Issue tracked by #522 and #523
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
Labels: bug

#511 [Hotfix] Fix Issue #506 and Issue #505
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterToPMServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouterToPMService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/exception/SubnetBindRouter.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
Labels: bug

#538 Fix basicTest.sh. /project/ was missing in the subnet query URL.
  scripts/basicTest.sh
Labels: bug, deployment and upgrade

#539 [Schema][DPM] Update protobuf contract and opType
  schema/proto3/common.proto
  schema/proto3/gateway.proto
  schema/proto3/vpc.proto
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/RouterService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/VpcService.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
Labels: contract

#541 Gateway Manager Micorservice
  lib/src/main/java/com/futurewei/alcor/common/executor/AsyncExecutor.java
  pom.xml
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SecurityGroupService.java
  services/gateway_manager/pom.xml
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/GatewayManagerApplication.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/config/ExceptionMsgConfig.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/config/SwaggerConfig.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/controller/AttachmentController.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/controller/GatewayController.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/controller/RoutingTableController.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/dao/GWAttachmentRepository.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/dao/GatewayRepository.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/entity/GWAttachment.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/entity/GatewaysWebJson.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/entity/ResourceType.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/entity/StatusEnum.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/exception/AttachmentNotFoundException.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/exception/GatewayEntityNotFoundException.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/service/AttachmentService.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/service/GatewayService.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/service/RouteTableService.java
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/utils/VerifyParameterUtils.java
  services/gateway_manager/src/main/resources/application.properties
  services/gateway_manager/src/test/java/com/futurewei/alcor/gatewaymanager/config/UnitTestConfig.java
  services/gateway_manager/src/test/java/com/futurewei/alcor/gatewaymanager/controller/GatewayControllerTest.java
  services/gateway_manager/src/test/java/com/futurewei/alcor/gatewaymanager/swagger/SwaggerJsonTest.java
  services/network_acl_manager/src/main/java/com/futurewei/alcor/networkaclmanager/service/implement/NetworkAclServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouterToPMService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
  services/subnet_manager/src/test/java/com/futurewei/alcor/subnet/SubnetControllerTests.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/GatewayEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/GatewayInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/GatewayInfoJson.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/GatewayIp.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/GatewayType.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/Route.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/RouteType.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/RoutingTable.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/VpcInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/VpcInfoJson.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/VpcInfoSub.java
  web/src/main/java/com/futurewei/alcor/web/entity/gateway/ZetaGatewayIpJson.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/SubnetEntity.java
  web/src/main/java/com/futurewei/alcor/web/restclient/GatewayManagerRestClinet.java
Labels: feature

#543 [Schema] Adding Gateway State into GS Message
  schema/proto3/gateway.proto
  schema/proto3/goalstate.proto
  schema/proto3/vpc.proto
Labels: contract
