Repository futurewei-cloud/alcor, pull requests merged in 2021-12, with the labels that each got.

#706 [Netw Config Manager] Support coexist of gRPC and REST APIs
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/NetworkConfigManagerApplication.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/GoalStateClient.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
  services/network_config_manager/src/test/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServerTest.java
Labels: bug

#709 [CI/CD] Improve handling of Jenkins error and exit
  scripts/busybox-ping-test/create_test_setup.py
  scripts/busybox-ping-test/helper_functions.py
  scripts/busybox-ping-test/ping_test.py
Labels: bug

#714 [Dependency] Upgrade guava package to 30.0+
  lib/pom.xml
Labels: dependencies

#707 [Tracing] Support Jaeger tracing in NCM and TC
  services/network_config_manager/pom.xml
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/GoalStatePersistenceServiceImpl.java
  services/network_config_manager/src/main/resources/application.properties
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/RequestManager.java
  services/pseudo_controller/pom.xml
  services/pseudo_controller/src/main/java/com/futurewei/alcor/pseudo_controller/pseudo_controller.java
  web/src/main/java/com/futurewei/alcor/web/restclient/NetworkConfigManagerRestClient.java
Labels: enhancement

#713 [DPM] Refactor db/cache codes to support GoalStateV2 design
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCacheImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/PortHostInfoCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/RouterSubnetsCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/SubnetPortsCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/InternalSubnetRouterMap.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/MulticastGoalStateV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/UnicastGoalStateV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImplV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/RouterService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NeighborProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterToDPMServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/NeutronRouterService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouterToDPMService.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortHostInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/InternalSubnetPorts.java
Labels: enhancement, feature
