Repository futurewei-cloud/alcor, pull requests merged in 2021-07, with the labels that each got.

#658 [Router Mgr] Remove transaction for a single cache operation
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteEntryRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteTableRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouterExtraAttributeRepository.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouterRepository.java
Labels: bug

#659 [Network Config Mgr] Cache Writing Optimization
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/HostResourceMetadataCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/GoalStatePersistenceServiceImpl.java
Labels: enhancement

#637 [Communication] gRPC channel/stub pool and keepalive for channels
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
Labels: enhancement

#643 [Documentation] Alcor performance test plan
  docs/test/images/Jaeger-vpc-creation.PNG
  docs/test/images/NetData-monitor.png
  docs/test/perfTestPlan.adoc
Labels: documentation, perf testing

#655 [RM] Separate getOrCreateVPCRouter into GET and POST two APIs
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/exception/CanNotFindRouter.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/exception/VpcRouterAlreadyExist.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouterService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/utils/RouteManagerUtil.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/VpcRouterTests.java
Labels: bug

#660 [Subnet] add try catch in delete subnet for subnet routing rule deletion if routing table is not exist
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
Labels: bug

#624 [Route Mgr] Verify and fix routing rule update in RM
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/exception/DestinationSame.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/exception/NeutronRouteTableIsNull.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterToDPMServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterToPMServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/NeutronRouterService.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/NeutronRouterTests.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/VpcRouterTests.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/RouteTable.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/Router.java
Labels: bug

#661 [Subnet Mgr] Fix gateway port duplicated creation issue
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/config/UnitTestConfig.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/utils/SubnetManagementUtil.java
  services/subnet_manager/src/test/java/com/futurewei/alcor/subnet/SubnetControllerTests.java
Labels: bug

#670 Warm up gRPC channels and add log for NCM performance analysis
  lib/src/main/java/com/futurewei/alcor/common/db/CacheFactory.java
  services/network_config_manager/Dockerfile
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/VpcResourceCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/entity/VpcResourceMeta.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/GoalStatePersistenceServiceImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/OnDemandServiceImpl.java
  services/network_config_manager/src/main/resources/application.properties
  services/network_config_manager/src/test/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServerTest.java
  services/pseudo_controller/src/main/java/com/futurewei/alcor/pseudo_controller/pseudo_controller.java
Labels: enhancement, logging

#671 [Data Plane Mgr] Allow empty routing table when creating router state
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/RouterService.java
Labels: Regression, bug

#672 [K8s Deployment] Add missing config in NCM yaml file
  kubernetes/services/network_config_manager.yaml
Labels: deployment and upgrade, k8s
