Repository futurewei-cloud/alcor, pull requests merged in 2021-04, with the labels that each got.

#582 [Network Config Mgr] Integrate NMM and NCM.
  lib/src/main/java/com/futurewei/alcor/common/db/ICache.java
  scripts/json/nodes-upload.json
  scripts/test/nmm-ncm-test.sh
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/controller/NetworkConfigController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/dao/NodeRepository.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/request/BulkCreateNodeInfoRequest.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/request/CreateNodeInfoRequest.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/request/DeleteNodeInfoRequest.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/request/UpdateNodeInfoRequest.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/utils/NodeManagerConstant.java
  web/src/main/java/com/futurewei/alcor/web/restclient/NetworkConfigManagerRestClient.java
Labels: enhancement, feature

#575 [Build/Test] Alcor busybox pingtest
  .gitignore
  scripts/alcor_services.sh
  scripts/test-automation/README.md
  scripts/test-automation/alcor_services.ini
  scripts/test-automation/busybox_alcor_api_calls.py
  scripts/test-automation/busybox_container_ops.py
  scripts/test-automation/busybox_helper_functions.py
  scripts/test-automation/busybox_ping_test.py
  services/data_plane_manager/src/main/resources/application.properties
Labels: build related, environment setup

#587 [Port Mgr] Fix the status return from port update for Nova
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
Labels: bug

#584 [Network Config Mgr] Add cache basic entities
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/HostResourceMetadataCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/NodeInfoCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/ResourceStateCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/VpcResourceCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/constant/Constants.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/entity/ResourceMeta.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/entity/VpcResourceMeta.java
Labels: feature

#593 [Fix Bug] Add device id and device owner in DPM UT
  lib/pom.xml
  services/data_plane_manager/src/main/resources/application.properties
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/config/TestConfig.java
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/DpmTest.java
Labels: bug

#585 Updates to busybox ping test scripts to include two subnet test case
  scripts/busybox-ping-test/README.md
  scripts/busybox-ping-test/alcor_services.ini
  scripts/busybox-ping-test/container_ops.py
  scripts/busybox-ping-test/create_test_cases.py
  scripts/busybox-ping-test/create_test_setup.py
  scripts/busybox-ping-test/helper_functions.py
  scripts/busybox-ping-test/ping_test.py
  scripts/busybox-ping-test/prepare_payload.py
  scripts/test-automation/alcor_services.ini
  scripts/test-automation/busybox_alcor_api_calls.py
  scripts/test-automation/busybox_container_ops.py
  scripts/test-automation/busybox_helper_functions.py
  scripts/test-automation/busybox_ping_test.py
Labels: build related

#599 [Route Manager] Fix L3 e2e issues for Neutron Router
  lib/pom.xml
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/exception/RouterHasMultipleVPCs.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/NeutronRouterService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/utils/RouteManagerUtil.java
Labels: bug

#598 [Node Mgr] Node Manager Interface for NCM Registration
  lib/pom.xml
  scripts/json/nodes-upload.json
  scripts/test/nmm-ncm-test.sh
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/NodeInfoCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/NodeInfoCache.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/controller/NodeController.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/dao/NcmInfoRepository.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/dao/NodeRepository.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/request/BulkCreateNodeInfoRequest.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/request/DeleteNodeInfoRequest.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeServiceImpl.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/utils/NodeManagerConstant.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/config/UnitTestConfig.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/NodeInfo.java
  web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/NetworkConfigManagerRestClient.java
Labels: bug

#602 [Data Plane Mgr] Add new ResourceOperation list to NetworkConfig
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/ResourceOperation.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/v2/NetworkConfiguration.java
Labels: bug, contract

#603 [Port Mgr] Support multiple ResourceOperation types
  lib/src/main/java/com/futurewei/alcor/common/utils/CommonUtil.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
  web/src/main/java/com/futurewei/alcor/web/entity/dataplane/ResourceOperation.java
Labels: enhancement, feature
