Repository futurewei-cloud/alcor, pull requests merged in 2021-05, with the labels that each got.

#605 [Port Mgr] Fix router resource operation type
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
Labels: bug

#606 [Test Script] Update busybox ping test to run from Jenkins
  scripts/alcor_services.sh
  scripts/busybox-ping-test/alcor_services.ini
  scripts/busybox-ping-test/container_ops.py
  scripts/busybox-ping-test/create_test_cases.py
  scripts/busybox-ping-test/create_test_setup.py
  scripts/busybox-ping-test/helper_functions.py
  scripts/busybox-ping-test/ping_test.py
  scripts/busybox-ping-test/prepare_payload.py
Labels: environment setup

#594 [Data Plane Mgr] Manage Topic for GroupNode-Topic Mode
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/NodeInfoCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/NodeTopicCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/TopicManager.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/utils/NodeManagerConstant.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/machine.json
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/NodeManagerProxy.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/NodeInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/topic/NodeTopicInfo.java
  web/src/main/java/com/futurewei/alcor/web/entity/topic/VpcTopicInfo.java
Labels: enhancement, feature

#609 [Test Script] Update readme of busybox pingtest
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/00_vpm_default_table
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/01_nm_ip_mac_aca1
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/01_nm_ip_mac_aca2
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/02_snm
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/03_router
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/04_sgm
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca1
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca1_post_limited
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca1_put_limited
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca2
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca2_post_limited
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca2_put_limited
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca3
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/05_pm_aca4
  scripts/busybox-ping-test-alcor-apis/01_one_subnet/project_info
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/00_vpm_default_table
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/01_nm_ip_mac_aca1
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/01_nm_ip_mac_aca2
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/02_snm_1
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/02_snm_2
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/03_router
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/03_router_interface
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/04_sgm
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/05_pm_s1_aca1
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/05_pm_s1_aca2
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/05_pm_s1_aca3
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/05_pm_s2_aca1
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/05_pm_s2_aca2
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/05_pm_s2_aca3
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/project_info
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/00_vpm_default_table
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/01_nm_ip_mac_aca1
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/01_nm_ip_mac_aca2
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/02_snm
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/04_sgm1
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/04_sgm2
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/05_pm_sg1_aca1
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/05_pm_sg2_aca2
  scripts/busybox-ping-test-alcor-apis/03_two_security_groups/project_info
  scripts/busybox-ping-test-alcor-apis/cleanup_bb_container.sh
  scripts/busybox-ping-test-alcor-apis/create_bb_container.sh
  scripts/busybox-ping-test/README.md
Labels: cicd, environment setup

#610 [Test Script] Update Alcor ping test case with 2 subnets
  scripts/busybox-ping-test-alcor-apis/02_two_subnets/project_info
Labels: cicd, deployment and upgrade

#617 [Deployment] Node upload yaml fix
  kubernetes/services/deleteYaml.sh
  kubernetes/services/network_config_manager.yaml
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
Labels: bug

#611 [Documentation] Add Alcor transaction design document
  docs/modules/ROOT/pages/db_services/alcor-transactions.adoc
Labels: documentation

#612 [Schema Change] Add gRPC channel to notify node subscribe MQ
  schema/proto3/subscribeinfoprovisioner.proto
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/NodeSubscribeClient.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/NodeSubscribeClientImpl.java
Labels: feature, schema

#614 [Data Plane Mgr] Fix DPM2.0 end-to-end L2/L3 neighbor
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCacheImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DhcpService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/ResourceService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/RouterService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouterService.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/NeutronRouterTests.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/VpcRouterTests.java
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java
  web/src/main/java/com/futurewei/alcor/web/entity/subnet/InternalSubnetPorts.java
Labels: bug

#618 [CI/CD] Jenkins test script fix
  scripts/busybox-ping-test/helper_functions.py
Labels: bug, cicd

#619 [Data Plane Mgr] Fix GoalState for L3 neighbors on the same host
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
Labels: bug

#620 [CI/CD] Jenkins fix
  scripts/busybox-ping-test/container_ops.py
  scripts/busybox-ping-test/create_test_cases.py
Labels: bug, cicd

#621 [RM & PM] Add/delete gateway port workflow update
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterToPMServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/NeutronRouterService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouterToPMService.java
  web/src/main/java/com/futurewei/alcor/web/entity/route/RouterUpdateInfo.java
Labels: enhancement, feature

#622 [Deployment] Add Gateway manager cleanup in K8s deployment script
  kubernetes/services/deleteYaml.sh
Labels: deployment and upgrade, k8s

#623 [CI/CD E2E] Improve ping test script
  scripts/busybox-ping-test/container_ops.py
  scripts/busybox-ping-test/create_test_cases.py
  scripts/busybox-ping-test/helper_functions.py
Labels: bug, cicd
