Repository futurewei-cloud/alcor, pull requests merged in 2021-03, with the labels that each got.

#549 [Port Mgr] Handle internal DPM result list
  lib/src/main/java/com/futurewei/alcor/common/enumClass/StatusEnum.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DpmController.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/CreateNetworkConfigRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/UpdateNetworkConfigRequest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortService.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
  web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
Labels: P1, enhancement

#551 [Schema] Protobuf v2 Schema for Network Configuration Manager
  schema/proto3/common.proto
  schema/proto3/goalstate.proto
  schema/proto3/goalstateprovisioner.proto
Labels: contract

#552 [DPM] Revert change back to PUT for createNetworkConfiguration
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DpmController.java
Labels: P0, bug

#554 [Schema] Add Id field in DHCP state
  .gitignore
  schema/proto3/dhcp.proto
Labels: schema

#555 [Data-Plane Mgr] Fix DPM NPE and gRPC issues.
  services/data_plane_manager/pom.xml
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
Labels: bug

#559 [Schema] Support multiple same-type resources per host
  schema/proto3/goalstate.proto
  schema/proto3/router.proto
Labels: schema

#564 [Data-Plane Mgr] Fix missing subnet entity in multicast GoalState
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java
Labels: bug

#562 [Network Config Manager] Demo Code
  docs/modules/ROOT/images/cache_design.PNG
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/db_services/distributed_cache.adoc
  docs/modules/ROOT/pages/infra_services/data_plane_manager.adoc
  pom.xml
  services/data_plane_manager/src/main/resources/application.properties
  services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
  services/network_config_manager/.gitignore
  services/network_config_manager/Dockerfile
  services/network_config_manager/pom.xml
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/NetworkConfigManagerApplication.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/GoalStateClient.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/config/Config.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/controller/NetworkConfigController.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/entity/HostGoalState.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/NetworkConfigServer.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/util/NetworkConfigManagerUtil.java
  services/network_config_manager/src/main/resources/application.properties
  services/network_config_manager/src/test/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServerTest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/PortManagerApplication.java
Labels: feature

#550 [Message Queue] Design Update
  docs/modules/ROOT/images/MQportcreate.png
  docs/modules/ROOT/images/vpcGroup.png
  docs/modules/ROOT/pages/mq_services/message_queue_system.adoc
  docs/modules/ROOT/pages/mq_services/message_queue_system.html
  docs/modules/ROOT/pages/mq_services/message_queue_system.pdf
  docs/modules/ROOT/workflows/MQ_portcreate.puml
Labels: documentation

#568 [Documentation] Image update for alcor_build
  docs/README.md
  docs/modules/ROOT/images/alcor_build.JPG
  docs/modules/ROOT/images/alcor_build.png
Labels: documentation

#546 [Documentation] Network Configuration Manager design draft
  docs/modules/ROOT/images/network_config_manager_overview.png
  docs/modules/ROOT/images/network_config_manager_workflow.png
  docs/modules/ROOT/pages/infra_services/network_config_manager.adoc
  docs/modules/ROOT/pages/infra_services/network_config_manager.pptx
  docs/modules/ROOT/workflows/network_config_manager_workflow.puml
Labels: documentation

#566 [Network Config Manager] Demo - Part 2
  services/network_config_manager/Dockerfile
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/NetworkConfigManagerApplication.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/entity/HostGoalState.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/exception/UnexpectedHostNumException.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/util/DemoUtil.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/util/NetworkConfigManagerUtil.java
Labels: enhancement, feature

#563 [Node Metadata Mgr] Add NCM Id field to NodeInfo
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/NodeService.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
  services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/utils/NodeManagerConstant.java
  services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/NodeManagerProxy.java
  services/port_manager/src/test/java/com/futurewei/alcor/portmanager/config/UnitTestConfig.java
  web/src/main/java/com/futurewei/alcor/web/entity/node/NodeInfo.java
Labels: enhancement, feature

#571 [Data Plane Mgr] Add device id and owner in PortService
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
Labels: bug

#572 [Network Config Mgr] Add NodeInfo APIs
  scripts/json/updateNode.json
  scripts/test/ncmtest.sh
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/NodeInfoCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/controller/NetworkConfigController.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/NodeService.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/NodeServiceImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/util/Constants.java
Labels: feature

#574 [Network Config Mgr] Add NCM REST client for node registration
  services/network_config_manager/pom.xml
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/config/SwaggerConfig.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/controller/NetworkConfigController.java
  services/network_config_manager/src/main/resources/application.properties
  web/src/main/java/com/futurewei/alcor/web/restclient/NetworkConfigManagerRestClient.java
Labels: enhancement

#576 [Data-Plane Mgr] Fix Port Operation Type Mismatch Issue
  kubernetes/services/dpm_manager.yaml
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DpmController.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DhcpService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
  services/data_plane_manager/src/main/resources/application.properties
Labels: bug
