Repository futurewei-cloud/alcor, pull requests merged in 2021-08, with the labels that each got.

#664 [Data Plane Mgr] Support routing rules update and router state update
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/NeighborCache.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/RouterService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/exception/DestinationSame.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterToDPMServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/NeutronRouterService.java
  services/route_manager/src/main/resources/application.properties
  services/route_manager/src/test/java/com/futurewei/alcor/route/NeutronRouterTests.java
  web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
Labels: enhancement, feature

#673 Add VpcEntity cache TRANSACTIONAL to ignite_config
  kubernetes/services/ignite_config.xml
Labels: deployment and upgrade, k8s

#674 Jenkins Redeployment changes
  docs/modules/ROOT/pages/performance/Method-list--CPU-ncm.csv
  scripts/busybox-ping-test/alcor_services.ini
  scripts/busybox-ping-test/create_test_cases.py
  scripts/busybox-ping-test/helper_functions.py
  scripts/busybox-ping-test/ping_test.py
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
Labels: bug, deployment and upgrade

#676 [API] Add route table APIs to API Gateway
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/route/RouterRouteConfiguration.java
Labels: api

#675 [Deployments] Update service link configs for K8s yaml
  kubernetes/services/dpm_manager.yaml
  kubernetes/services/ignite_alcor.yaml
  kubernetes/services/ignite_config.xml
  kubernetes/services/vpc_manager.yaml
  services/elastic_ip_manager/src/main/resources/application.properties
Labels: deployment and upgrade, k8s

#677 [API Compatibility] Make Alcor router APIs compatible with Nova
  services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/route/RouterRouteConfiguration.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/test/java/com/futurewei/alcor/route/NeutronRouterTests.java
Labels: api

#678 [Jaeger] Fix tracing spans between functions and services in PM
  services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/RequestManager.java
Labels: tracing

#680 [Subnet Mgr] Allow to delete a subnet without a gateway port
  services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
Labels: bug, short-term fix
