Repository futurewei-cloud/alcor, pull requests merged in 2021-06, with the labels that each got.

#627 [Data Plane Mgr] Fix bug in processNeighborConfiguration for test scenario 5.
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/NeutronRouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
  services/route_manager/src/main/java/com/futurewei/alcor/route/service/NeutronRouterService.java
Labels: enhancement, feature

#629 [CI/CD E2E] Ping test s4 fix
  scripts/busybox-ping-test/container_ops.py
  scripts/busybox-ping-test/create_test_cases.py
  scripts/busybox-ping-test/ping_test.py
  scripts/busybox-ping-test/prepare_payload.py
Labels: cicd, environment setup

#634 [CI/CD E2E] Ping test s5 fix
  scripts/busybox-ping-test/alcor_services.ini
  scripts/busybox-ping-test/container_ops.py
  scripts/busybox-ping-test/create_test_cases.py
  scripts/busybox-ping-test/create_test_setup.py
  scripts/busybox-ping-test/helper_functions.py
  scripts/busybox-ping-test/ping_test.py
Labels: cicd

#642 [API Perf Enhancement] Optimize vpc create default segment table
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRangeRepository.java
  services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/SegmentServiceImpl.java
Labels: enhancement

#641 [CI/CD E2E] Ping test via API GW
  scripts/busybox-ping-test/alcor_services.ini
  scripts/busybox-ping-test/create_test_cases.py
  scripts/busybox-ping-test/create_test_setup.py
  scripts/busybox-ping-test/ping_test.py
Labels: cicd

#653 [Gateway Mgr] Update GatewayService.java to fix Issue #652
  services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/service/GatewayService.java
Labels: bug
