Repository futurewei-cloud/alcor, pull requests merged in 2022-02, with the labels that each got.

#734 Improve DPM and NCM performance
  kubernetes/db/ignite/ignite_alcor.yaml
  kubernetes/db/ignite/ignite_alcor_ip.yaml
  kubernetes/db/ignite/ignite_alcor_mac.yaml
  kubernetes/db/ignite/ignite_alcor_port.yaml
  kubernetes/db/ignite/ignite_config.xml
  kubernetes/db/ignite/ignite_ip_config.xml
  kubernetes/db/ignite/ignite_mac_config.xml
  kubernetes/db/ignite/ignite_port_config.xml
  kubernetes/services/api-gateway.yaml
  kubernetes/services/dpm_manager.yaml
  kubernetes/services/elastic_ip_manager.yaml
  kubernetes/services/gateway_manager.yaml
  kubernetes/services/mac_manager.yaml
  kubernetes/services/network_config_manager.yaml
  kubernetes/services/node_manager.yaml
  kubernetes/services/port_manager.yaml
  kubernetes/services/private_ip_manager.yaml
  kubernetes/services/quota_manager.yaml
  kubernetes/services/route_manager.yaml
  kubernetes/services/sg_manager.yaml
  kubernetes/services/subnet_manager.yaml
  kubernetes/services/vpc_manager.yaml
  lib/pom.xml
  lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteConfiguration.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImplV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  services/data_plane_manager/src/main/resources/application.properties
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/ResourceStateCache.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/ResourceInfo.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/GoalStatePersistenceServiceImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/ResourceInfoImpl.java
  services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/util/NetworkConfigManagerUtil.java
  services/network_config_manager/src/main/resources/application.properties
  services/port_manager/src/main/resources/application.properties
  web/src/main/java/com/futurewei/alcor/web/restclient/AbstractRestClient.java
  web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
Labels: perf testing, deployment and upgrade, k8s

#728 [DPM] Map vpcId to hostIp in MulticastGoalStateV2
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/group_node_mode/DataPlaneClientImplV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/vpc_mode/DataPlaneClientImplV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/FunctionMulticastGoalStateV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/FunctionUnicastGoalStateV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/MulticastGoalStateV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/UnicastGoalStateV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java
Labels: enhancement

#736 Fix ignite configuration
  kubernetes/db/ignite/ignite_config.xml
  kubernetes/db/ignite/ignite_ip_config.xml
  kubernetes/db/ignite/ignite_mac_config.xml
  kubernetes/db/ignite/ignite_port_config.xml
Labels: bug, deployment and upgrade, k8s

#739 Added in namespace field for ansible deploy script
  kubernetes/services/api-gateway.yaml
  kubernetes/services/dpm_manager.yaml
  kubernetes/services/elastic_ip_manager.yaml
  kubernetes/services/gateway_manager.yaml
  kubernetes/services/mac_manager.yaml
  kubernetes/services/network_config_manager.yaml
  kubernetes/services/node_manager.yaml
  kubernetes/services/port_manager.yaml
  kubernetes/services/private_ip_manager.yaml
  kubernetes/services/quota_manager.yaml
  kubernetes/services/route_manager.yaml
  kubernetes/services/sg_manager.yaml
  kubernetes/services/subnet_manager.yaml
  kubernetes/services/vpc_manager.yaml
Labels: k8s

#741 [DPM] Remove hostIps hashset from MulticastGoalstateV2
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/MulticastGoalStateV2.java
  services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
Labels: enhancement

#743 Test Controller Enhancements
  services/pseudo_controller/pom.xml
  services/pseudo_controller/src/main/java/com/futurewei/alcor/pseudo_controller/alcor_http_api_test/alcor_http_api_test.java
  services/pseudo_controller/src/main/java/com/futurewei/alcor/pseudo_controller/ncm_test/ncm_test.java
  services/pseudo_controller/src/main/java/com/futurewei/alcor/pseudo_controller/pseudo_controller.java
  services/pseudo_controller/src/main/resources/application.properties
Labels: enhancement
